### PR TITLE
python-gssapi 1.8.3

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Current package info**

| Channel | Downloads | Version | Platforms | License |
| --- | --- | --- | --- | --- |
| main | [Anaconda Downloads](https://anaconda.org/main/python-gssapi) | [Anaconda Version](https://anaconda.org/main/python-gssapi) | [Anaconda Platforms](https://anaconda.org/main/python-gssapi) | Anaconda License |

**Destination channel:** defaults

### Links

- [PKG-4530](https://anaconda.atlassian.net/browse/PKG-4530)
- release-notes: https://github.com/pythongssapi/python-gssapi/releases
- release-notes-tagged: https://github.com/pythongssapi/python-gssapi/releases/tag/v1.8.3
- license: https://github.com/pythongssapi/python-gssapi/blob/main/LICENSE.txt
- requirements-tagged:
  - https://github.com/pythongssapi/python-gssapi/blob/v1.8.3/pyproject.toml
  - https://github.com/pythongssapi/python-gssapi/blob/v1.8.3/setup.py

### Explanation of changes:

- Constrain `0001-fix-setup.patch` for `osx` only
- Fix the krb5 library path on Windows. The build fails if the path is `winkrb_path/lib/amd64`. But `winkrb_path/lib` is fine.
- Add `patch`/`m2-patch` to `build`
- Skip `py<37`
- Update/add `cython` and `krb5` pinnings in `host` and `run` 
- Add missing `setuptools` and `wheel`
- Add `pip check`
- Add `license_family`
- Add `description`

### Notes:

-

[PKG-4530]: https://anaconda.atlassian.net/browse/PKG-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on `win64`:
```
    File "C:\b\abs_8f7hppdz6h\croot\python-gssapi_1713943587923\_h_env\Lib\site-packages\setuptools\build_meta.py", 
      exec(code, locals())

    File "<string>", line 104, in <module>
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\b\\abs_8f7hppdz6h\\croot\\python-gssapi_1713943587923\\_h_env\\Library\\lib\\amd64'
```

**Comment by skupr-anaconda** [comment]
After applying a [patch](https://github.com/AnacondaRecipes/python-gssapi-feedstock/pull/1/files#diff-ae80c89905cf0b54a2e827d4adb9c6c1f9402c6cb5122dea5dd185628b7f3f71), there is a new error on `win64`:
```
  "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env\Library\lib /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env\libs /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\um\x64" /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env\Library\lib /LIBPATH:C:\b\abs_824xg03kuo\croot\python-gssapi_1713945206950\_h_env\Library\lib comerr64.lib engines-1_1.lib gssapi64.lib k5sprt64.lib kfwlogon.lib krb5_64.lib krbcc64.lib leashw64.lib libcrypto.lib libssl.lib sqlite3.lib xpprof64.lib /EXPORT:PyInit_misc build\temp.win-amd64-cpython-39\Release\gssapi/raw/misc.obj /OUT:build\lib.win-amd64-cpython-39\gssapi\raw\misc.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-39\Release\gssapi/raw\misc.cp39-win_amd64.lib

  LINK : fatal error LNK1181: cannot open input file 'engines-1_1.lib'
```

**Comment by skupr-anaconda** [comment]
After applying the second patch, I got a new error:
```
  "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env\Library\lib /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env\libs /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\um\x64" /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env\Library\lib /LIBPATH:C:\b\abs_439o3v84xs\croot\python-gssapi_1713946200745\_h_env\Library\lib bzip2.lib bzip2_static.lib comerr64.lib dde1.lib engines-1_1.lib ffi.lib gssapi64.lib itcl4.2.lib k5sprt64.lib kfwlogon.lib krb5_64.lib krbcc64.lib leashw64.lib libbz2.lib libbz2.lib libbz2.lib libbz2_static.lib libcrypto.lib libffi.dll.lib libffi.lib liblzma.lib liblzma_static.lib libssl.lib nmake.lib pkgconfig.lib reg1.lib sqlite3.36.lib sqlite3.lib tcl8.lib tcl8.lib tcl86t.lib tclConfig.lib tclooConfig.lib tclstub86.lib tdbc1.1.lib tdbcmysql1.1.lib tdbcodbc1.1.lib tdbcpostgres1.1.lib tdbcsqlite31.1.lib thread2.8.lib tk8.lib tk86t.lib tkstub86.lib xpprof64.lib z.lib zdll.lib zlib.lib zlibstatic.lib /EXPORT:PyInit_misc build\temp.win-amd64-cpython-310\Release\gssapi/raw/misc.obj /OUT:build\lib.win-amd64-cpython-310\gssapi\raw\misc.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\gssapi/raw\misc.cp310-win_amd64.lib

  LINK : fatal error LNK1181: cannot open input file 'dde1.lib'
```

**Comment by skupr-anaconda** [comment]
Two errors above were caused by a missing selector `# [not win]` in the `script` section

**Review by JamesRobertsonGames — APPROVED** [review]
Looks good to me! :+1:

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Pull request merged**
